### ISSUE TITLE
Error: spawn candle.exe ENOENT

### ISSUE THREAD

**Issue by JasminDreasond** [felixrieseberg/electron-wix-msi#14]
I'm trying to execute this script, but happen it.

var { MSICreator } = require('electron-wix-msi');

async function nya() {

    // Step 1: Instantiate the MSICreator
    const msiCreator = new MSICreator({
        appDirectory: __dirname + '/app',
        outputDirectory: __dirname + '/install',
        description: package.description,
        exe: package.name + "-" + package.version + "-setup",
        name: package.productName,
        manufacturer: "Tiny Jasmini",
        version: package.version,
        shortName: package.shortName,
        programFilesFolderName: package.productName,
        upgradeCode: package.name + "_tinyjsm"
    });

    // Step 2: Create a .wxs template file
    await msiCreator.create();

    // Step 3: Compile the template to a .msi file
    await msiCreator.compile();

}

nya();

electron-wix-msi: Using light.exe (3.11.1.2318) and candle.exe (3.11.1.2318)
creator.js:77
Error: spawn candle.exe ENOENT
util.js:1031
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

I need help :c

**Comment by flavienbwk** [comment]
Maybe this could help : https://github.com/felixrieseberg/electron-wix-msi/issues/1#issuecomment-416642865
