### ISSUE TITLE
LGHT0204: The target file <XXX> is installed in "[ProgramFilesFolder]\<app>" by two different components on an LFN system

### ISSUE THREAD

**Issue by tnyavdc** [felixrieseberg/electron-wix-msi#20]
I'm attempting to package a win32-x64 folder generated by `electron-forge package` but keep getting a wall of LGHT0204 errors on the compile command. The errors seem to reference files in node_modules. The MSI installer is still created, but the EXE it installed does not open.

### Error log (snippet)
```
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(35774) : error LGHT0204 : ICE30: The target file 'split.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_099c4394_e9dc_4322_8755_09fa0b5ab312' and '_8d1ab663_f699_4ce4_b73f_d56d2a342371'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(3890) : error LGHT0204 : ICE30: The target file 'split.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_099c4394_e9dc_4322_8755_09fa0b5ab312' and '_8d1ab663_f699_4ce4_b73f_d56d2a342371'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(35774) : error LGHT0204 : ICE30: The target file 'split.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_2190229f_9b63_4fca_83e2_e4052571eecf' and '_8d1ab663_f699_4ce4_b73f_d56d2a342371'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(5819) : error LGHT0204 : ICE30: The target file 'split.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_2190229f_9b63_4fca_83e2_e4052571eecf' and '_8d1ab663_f699_4ce4_b73f_d56d2a342371'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(35774) : error LGHT0204 : ICE30: The target file 'split.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_8b004414_d9df_41d1_a7a5_f7d8e3634b53' and '_8d1ab663_f699_4ce4_b73f_d56d2a342371'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(17672) : error LGHT0204 : ICE30: The target file 'split.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_8b004414_d9df_41d1_a7a5_f7d8e3634b53' and '_8d1ab663_f699_4ce4_b73f_d56d2a342371'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(35774) : error LGHT0204 : ICE30: The target file 'split.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_4b6597ff_521f_4cb1_a082_e31391a74154' and '_8d1ab663_f699_4ce4_b73f_d56d2a342371'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(34424) : error LGHT0204 : ICE30: The target file 'split.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_4b6597ff_521f_4cb1_a082_e31391a74154' and '_8d1ab663_f699_4ce4_b73f_d56d2a342371'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(35777) : error LGHT0204 : ICE30: The target file 'kvligyvc.js|to-primitive.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_1898a8ab_3da4_4740_a923_d67e350689c9' and '_cc5cf05b_9e5e_4c7b_a869_557548954bad'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(34427) : error LGHT0204 : ICE30: The target file 'kvligyvc.js|to-primitive.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_1898a8ab_3da4_4740_a923_d67e350689c9' and '_cc5cf05b_9e5e_4c7b_a869_557548954bad'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(35780) : error LGHT0204 : ICE30: The target file 'gms94rl3.js|to-string-tag.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_1de9fe18_755e_491e_b839_6cb2f798c4f2' and '_09600d2a_b33c_4c28_8d63_f73955267ba0'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(34430) : error LGHT0204 : ICE30: The target file 'gms94rl3.js|to-string-tag.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_1de9fe18_755e_491e_b839_6cb2f798c4f2' and '_09600d2a_b33c_4c28_8d63_f73955267ba0'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(35783) : error LGHT0204 : ICE30: The target file 'nci4hfev.js|unscopables.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_c88713fc_d674_4c84_947a_fa0c82e5e956' and '_90006e73_db0a_457f_aa62_801b7b86ae20'. This breaks component reference counting.
C:\Users\josia\fire-flower-cms\out\installer64\fafcms.wxs(34433) : error LGHT0204 : ICE30: The target file 'nci4hfev.js|unscopables.js' is installed in '[ProgramFilesFolder]\FF CMS\' by two different components on an LFN system: '_c88713fc_d674_4c84_947a_fa0c82e5e956' and '_90006e73_db0a_457f_aa62_801b7b86ae20'. This breaks component reference counting.
```

### Versions
**electron-wix-installer:** 2.0.3
**electron-forge:** 5.2.2

**Comment by AviramNahon** [comment]
same here...

**Comment by Feirell** [comment]
This error seems to be from some file finding / placing problem.

This was my error listing:

```
electron-wix-msi: Using light.exe (3.11.1.2318) and candle.exe (3.11.1.2318)
Error: Could not create msi file. Code: 204 StdErr:  StdOut: Windows Installer XML Toolset Linker version 3.11.1.2318
Copyright (c) .NET Foundation and contributors. All rights reserved.

C:\path\to\output\folder\kittens.wxs(267) : error LGHT0204 : ICE30: The target file 'libEGL.dll' is installed in '[ProgramFilesFolder]\Kittens\' by two different components on an SFN system: '_libEGL.dll_0712f698_5058_45ce_8c79_305474a85788' and '_libEGL.dll_41905d05_1e66_4f9c_a39a_fbf440f0b218'. This breaks component reference counting.
C:\path\to\output\folder\kittens.wxs(78) : error LGHT0204 : ICE30: The target file 'libEGL.dll' is installed in '[ProgramFilesFolder]\Kittens\' by two different components on an SFN system: '_libEGL.dll_0712f698_5058_45ce_8c79_305474a85788' and '_libEGL.dll_41905d05_1e66_4f9c_a39a_fbf440f0b218'. This breaks component reference counting.
C:\path\to\output\folder\kittens.wxs(267) : error LGHT0204 : ICE30: The target file 'libEGL.dll' is installed in '[ProgramFilesFolder]\Kittens\' by two different components on an LFN system: '_libEGL.dll_0712f698_5058_45ce_8c79_305474a85788' and '_libEGL.dll_41905d05_1e66_4f9c_a39a_fbf440f0b218'. This breaks component reference counting.
C:\path\to\output\folder\kittens.wxs(78) : error LGHT0204 : ICE30: The target file 'libEGL.dll' is installed in '[ProgramFilesFolder]\Kittens\' by two different components on an LFN system: '_libEGL.dll_0712f698_5058_45ce_8c79_305474a85788' and '_libEGL.dll_41905d05_1e66_4f9c_a39a_fbf440f0b218'. This breaks component reference counting.
C:\path\to\output\folder\kittens.wxs(270) : error LGHT0204 : ICE30: The target file '4kuikhe_.dll|libGLESv2.dll' is installed in '[ProgramFilesFolder]\Kittens\' by two different components on an LFN system: '_libGLESv2.dll_8dddebfb_9a4c_4a64_a9ab_0187adba0164' and '_libGLESv2.dll_1c4081ff_5c5f_4695_ade2_20d133d83c5e'. This breaks component reference counting.
C:\path\to\output\folder\kittens.wxs(81) : error LGHT0204 : ICE30: The target file '4kuikhe_.dll|libGLESv2.dll' is installed in '[ProgramFilesFolder]\Kittens\' by two different components on an LFN system: '_libGLESv2.dll_8dddebfb_9a4c_4a64_a9ab_0187adba0164' and '_libGLESv2.dll_1c4081ff_5c5f_4695_ade2_20d133d83c5e'. This breaks component reference counting.

    at MSICreator.<anonymous> (\node_modules\electron-wix-msi\lib\creator.js:161:23)
    at Generator.next (<anonymous>)
    at fulfilled (\node_modules\electron-wix-msi\lib\creator.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Fixed it for me by using `path` to correctly resolve the paths:

```
const { MSICreator } = require('electron-wix-msi');
const path = require('path');

(async () => {
    // Step 1: Instantiate the MSICreator
    const msiCreator = new MSICreator({
        appDirectory: path.resolve('.\\test-app-win32-x64'),
        description: 'My amazing Kitten simulator',
        exe: 'kittens',
        name: 'Kittens',
        manufacturer: 'Kitten Technologies',
        version: '1.1.2',
        outputDirectory: path.resolve('.\\out')
    });

    // Step 2: Create a .wxs template file
    await msiCreator.create();

    // Step 3: Compile the template to a .msi file
    await msiCreator.compile();
})()
```
