### ISSUE TITLE
'light' is not recognized as an internal or external command, operable program or batch file. 'candle' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Robin-Sch** [felixrieseberg/electron-wix-msi#48]
I added it to the path but it still doesn't work. I added it both to my user path and the pc path.

**Comment by ctrlventure** [comment]
You usually need to restart the power shell for it to take into account the new PATH variable.

**Comment by qnlbnsl** [comment]
first, check if you can even call candle and light by themselves in your shell. If not then look for Wix documentation. This issue is more so related to your environment rather than this package.

**Comment by gabrielyotoo** [comment]
What if I can call light and candle, but when I try to make the app, it says it cannot find?

```txt
$ light
Windows Installer XML Toolset Linker version 3.14.1.8722
Copyright (c) .NET Foundation and contributors. All rights reserved.
 usage:  light.exe [-?] [-b bindPath] [-nologo] [-out outputFile] objectFile [objectFile ...] [@responseFile]
   ...
$ candle
Windows Installer XML Toolset Compiler version 3.14.1.8722
Copyright (c) .NET Foundation and contributors. All rights reserved.
 usage:  candle.exe [-?] [-nologo] [-out outputFile] sourceFile [sourceFile ...] [@responseFile]
  ...
$ yarn make
❯ Checking your system
❯ Checking git exists
❯ Checking node version
❯ Checking packageManager version
...
'light' is not recognized as an internal or external command,
operable program or batch file.
'candle' is not recognized as an internal or external command,
operable program or batch file.
It appears that electron-wix-msi cannot find candle.exe or light.exe.
Please consult the readme at https://github.com/felixrieseberg/electron-wix-msi
for information on how to install the Wix toolkit, which is required.
✖ Making a wix distributable for win32/x64 [FAILED: Could not find light.exe or candle.exe]
✖ Making distributables [FAILED: Could not find light.exe or candle.exe]
An unhandled rejection has occurred inside Forge:
Error: Could not find light.exe or candle.exe
at MSICreator.<anonymous> (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\electron-wix-msi\lib\creator.js:153:23)
    at Generator.next (<anonymous>)
    at C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\electron-wix-msi\lib\creator.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\electron-wix-msi\lib\creator.js:4:12)
    at MSICreator.compile (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\electron-wix-msi\lib\creator.js:146:16)
    at MakerWix.make (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\@electron-forge\maker-wix\dist\MakerWix.js:44:43)
    at async C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\@electron-forge\core\dist\api\make.js:187:55
    at async _Task.taskFn (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\@electron-forge\tracer\dist\index.js:58:20)
    at async _Task.run (C:\GitLab-Runner\builds\y-seikou\ci-windows-test\node_modules\listr2\dist\index.cjs:2063:11)
```
